--ALTER TABLE me.Expense DROP constraint FK_Expense_Currency
--ALTER TABLE me.Expense DROP COLUMN CurrencyID
--ALTER TABLE me.BagCurrency DROP constraint  FK_CategoryCurenncy_Category
--ALTER TABLE me.BagCurrency DROP constraint FK_CategoryCurenncy_Currency
--ALTER TABLE me.Income DROP constraint FK_Income_Currency
--DROP TABLE me.BagCurrency
--DROP TABLE me.Currency